# CLASE 07 Creación de Arrays
## Prof. Andrés Mena Abarca
### Estudiantes: Katherine Bianco V.
url:https://github.com/Xkat23/Programacion-Python-Basico-GRUPO-1---6181133432/blob/4e1bf5628f80df89afc3cbf00ad64f3e6b54a107/Estudiantes/Katherine%20Bianco/Clase%2007/Practica_6.ipynb

### Crear un array a partir de una lista

In [6]:
import numpy as np




2.2.2


### Crear un array de ceros de tamaño 5x5

In [8]:
#Código crear un array de ceros de tamaño 5x5
array_ceros = np.zeros((5,5))
print(array_ceros)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [15]:
#Código crear un array de unos de tamaño 3x3
array_unos = np.ones((5,3))
print(array_unos)



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [19]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
array_linear = np.linspace(0,9,10)
print(array_linear)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [21]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
array_reto = np.linspace(0,1,6)
print(array_reto)

[0.  0.2 0.4 0.6 0.8 1. ]


# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [29]:
array_salario = np.array([50,40,20])
array_propinas = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays

# Salida
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)
'''
suma = array_salario + array_propinas
resta = array_salario - array_propinas
multi = array_salario * array_propinas
division = array_salario / array_propinas
print(suma)
print(resta)
print(multi)
print(division)

[56 44 29]
[44 36 11]
[300 160 180]
[ 8.33333333 10.          2.22222222]


In [32]:
array_salario = np.array([[50,40,20], [2,3,4]])
array_propinas = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays

# Salida
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)
'''
suma = array_salario + array_propinas
resta = array_salario - array_propinas
multi = array_salario * array_propinas
division = array_salario / array_propinas
print(suma)
print(resta)
print(multi)
print(division)

[[56 44 29]
 [ 8  7 13]]
[[44 36 11]
 [-4 -1 -5]]
[[300 160 180]
 [ 12  12  36]]
[[ 8.33333333 10.          2.22222222]
 [ 0.33333333  0.75        0.44444444]]


In [33]:
#Calcular el producto punto de dos arrays


In [ ]:
#Transponer un array


# Operaciones Estadísticas

In [41]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])


# Calcular la media
media = np.mean(array_numeros)
print(f'La media aritmetica es: {media}')

# Calcular la suma
suma = np.sum(array_numeros)
print(f'La suma de la coleccion de datos es: {suma}')

# Calcular el valor mínimo
minimo = np.min(array_numeros)
print(f'El min de la coleccion de datos es: {minimo}')

# Calcular el valor máximo
maximo = np.max(array_numeros)
print(f'El max de la coleccion de datos es: {maximo}')

'''
# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)
'''


La media aritmetica es: 3.0
La suma de la coleccion de datos es: 15
El min de la coleccion de datos es: 1
El max de la coleccion de datos es: 5


'\n# Mostrar los resultados\nprint("La media es:", media)\nprint("La suma es:", suma)\nprint("El valor mínimo es:", valor_minimo)\nprint("El valor máximo es:", valor_maximo)\n'

In [43]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_reshapeado = array_original.reshape(2,3)
print(array_reshapeado)

'''
# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)
'''

[[1 2 3]
 [4 5 6]]


'\n# Imprimir el array original y el reshapeado\nprint("Array original:", array_original)\nprint("Array reshapeado:", array_reshapeado)\n'

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

#print(determinante)

### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3


# Calcular la matriz inversa


# Imprimir la matriz inversa



### Calcular los valores propios y vectores propios de una matriz 4x4

In [ ]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

# Funciones Universales

In [ ]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos


# Calcular el coseno de los ángulos


# Calcular la exponencial de los ángulos


# Calcular el logaritmo natural de los ángulos




In [ ]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array


# Obtener la última columna del array
  # [3, 6, 9]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

# Imprimir los subconjuntos de datos extraídos


# Generación de Números Aleatorios

In [ ]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)



## Ejercicos reales o prácticos

In [51]:
mariana = np.array([7,9,2])


avatar = np.array([10,1,5]) #Mas accion y menos comedia
brave_heart = np.array([8,1,7]) # Mas accion y menos accion


#Calcular la similitud de cada pelicula con los gusto de Mariana


similitud_p1 = np.dot(mariana,avatar)
similitud_p2 = np.dot(mariana,brave_heart)


print(f'Similitud de preferencias Avatar: {similitud_p1}')
print(f'Similitud de preferencias Brave Heart: {similitud_p2}')


if similitud_p1 > similitud_p2:
    print('Recomendamos Avatar')
else:
    print('Recomendamos Brave Heart')

Similitud de preferencias Avatar: 89
Similitud de preferencias Brave Heart: 79
Recomendamos Avatar


## Caso de estudio Correlación

In [55]:
import numpy as np

#Dtos Tipo Cambio de Dolar Ultimos 10 meses | IPC, metrica mensual

tipo_cambio = np.array([506.96,505.00,504.27,505.27,506.23,506.58,506.90,505.5,506.40,505.34])
ipc = ([109.46,109.55,109.71,109.33,109.54,109.56,109.36,110.39,110.79,109.36])

#Calcular coeficiente de correlacion
correlacion = np.corrcoef(tipo_cambio,ipc)[0,1]
print(f'Coeficiente de corelacion: {correlacion:.2f}') #.2f es para disminuir la cantidad de decimales

Coeficiente de corelacion: 0.02


## Caso 3 Estudio de Horas vrs Notas


In [59]:
#Datos: Horas de estudio y Notas obtenidas
horas_estudio = np.array([1,2,3,3,4,4,5,6,5,6]) #Horas de estudio

notas = np.array([50,55,60,67,72,81,85,90,89,91])#Notas Obtenidas

#Calculo crecimiento del promedio del puntaje por hora de estudio
diferencias_notas = np.diff(notas)#Diferencia entre notas consecutivas
incremento_notas = np.mean(diferencias_notas)
#Estimacion del puntaje si estudio 12 horas
proyeccion_estudio = 12
nota_estimada = horas_estudio - horas_estudio[-1]

print(diferencias_notas)
print(incremento_notas)


[ 5  5  7  5  9  4  5 -1  2]
4.555555555555555


In [68]:
#Datos: Horas de estudio y Notas obtenidas
horas_estudio = np.array([1,2,3,3,4,4,5,6,5,6]) #Horas de estudio

notas = np.array([50,55,60,67,72,81,85,90,89,91])#Notas Obtenidas

#Calculo crecimiento del promedio del puntaje por hora de estudio
diferencias_notas = np.diff(notas)#Diferencia entre notas consecutivas
incremento_notas = np.mean(diferencias_notas)

#Estimacion del puntaje si estudio 12 horas
proyeccion_estudio = 12

nota_estimada = (proyeccion_estudio - horas_estudio[-1]) * incremento_notas + max(notas)
nota_estimada_minimo = (min(horas_estudio) - proyeccion_estudio) * incremento_notas + min(notas)

print(f'El incremento del promedio {incremento_notas:.2f}')
print(nota_estimada)
print(nota_estimada_minimo)


El incremento del promedio 4.56
118.33333333333333
-0.11111111111110716
